laladupsi/laladupsi/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("portfolio.urls")),
]

laladupsi/portfolio/urls.py
from django.urls import include, path
from django.contrib import admin
from .views import *

urlpatterns = [
    path('', index),
    path('facts.html/',facts),
    path('facts.html/index.html/',index),
]

laladupsi/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("portfolio.urls")),
]

portfolio/urls.py
from django.urls import include, path
from django.contrib import admin
from .views import *

app_name = 'portfolio'

urlpatterns = [
    path('', index),
    path('jadwalku/', message_post, name='message_post'),
    path('jadwalku/del',delete_recs,name='delete_recs')

]

laladupsi/portfolio/models.py
from django.db import models

# Create your models here.

portfolio/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

# Create your models here.
class Jadwal(models.Model):
    name = models.CharField(max_length=50)
    place = models.CharField(max_length=30)
    category = models.CharField(max_length=30)
    date = models.DateField()
    time = models.DateTimeField(default=timezone.now)

portfolio/forms.py
from django import forms


class JadwalPribadi(forms.Form):
    attrs={'class':'form-control',}
    attrs_time = {'class':'form-control','type':'date'}
    name = forms.CharField(label='Nama', required=True,
        max_length=50,empty_value='Anonymous',)
        #widget=forms.TextInput(attrs=attrs))
    place = forms.CharField(label='Place', required=True,
        max_length=30,empty_value='Anonymous',)
        #widget=forms.TextInput(attrs=attrs))
    category = forms.CharField(label='Category', required=True,
        max_length=30,empty_value='Anonymous',)
        #widget=forms.TextInput(attrs=attrs))
    date = forms.DateTimeField(label='Date, time', required=True,
        widget=forms.DateInput(attrs=attrs_time))

laladupsi/portfolio/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return render(request, 'index.html')

def facts(request):
    return render(request,'facts.html')

portfolio/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import JadwalPribadi
from .models import Jadwal

response = {}
def index(request):
    form = JadwalPribadi()
    response['form'] = form
    hasil = Jadwal.objects.all()
    response['result']=hasil
    return render(request, 'jadwal.html', response)

def facts(request):
    return render(request,'facts.html')

def message_post(request):
    form = JadwalPribadi(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['day'] = request.POST['day']
        response['place'] = request.POST['place']
        response['category'] = request.POST['category']
        response['date'] = request.POST['date']
        message = JadwalPribadi(name=response['name'],day=response['day'],place=response['place'],
            category=response['category'], date=response['date'])
        message.save()

        html = 'jadwal.html'
        return render(request,html,response)
    else:
        return render(request,'jadwal.html',response)

def delete_recs(request):
    Jadwal.objects.all().delete()
    context= {}
    return render(request, 'jadwal.html', context)
# def show_result(request):
#     result = Jadwal.objects.all()
#     response['result']=result
#     return render(request,'jadwal.html', response)

laladupsi/portfolio/templates/facts.html
<!DOCTYPE html>
{% extends "header.html" %}
<html>
<head>
    {% load static %}
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    {% block title %}Facts!{% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>
<body>
    {% block content %}
        <div>
            Teaching Assistant at Fasilkom UI<br>
            Staff at BEM Fasilkom UI
        </div>
    {% endblock %}
</body>
</html>

laladupsi/portfolio/templates/header.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'portfolio/css/header.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!--<script src="main.js"></script>-->
</head>
<body>
<nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html">Hello</a>
            </div>
        
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="facts.html">Facts about me</a></li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                <input type="text" class="form-control" placeholder="Get to know me!">
                </div>
                <button type="submit" class="btn .btn-primary.outline" id="search-btn">Search</button>
            </form>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
        </nav>
    {% block content %}{% endblock %}
</body>
</html>

laladupsi/portfolio/templates/index.html
<!DOCTYPE html>
{% extends "header.html" %}
<html>
<head>
    {% load static %}
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}Hello!{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'portfolio/css/index.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    
    
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!--<style>
        body {
            font-family: Arial, Helvetica, sans-serif;
        }
    </style>-->
</head>
{% block content %}
    <body>
        <div>
            <img id="mypic" src="{% static 'portfolio/img/8565053043380.jpg' %}">
            <h1>Nabila Fathia Z</h1>
            <h1>Student at Fasilkom UI</h1>
        </div>
    </body>
{% endblock %}

</html>

portfolio/templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'portfolio/css/header.css' %}">
    <!--<script src="main.js"></script>-->
</head>
<body>
    <nav class="navbar navbar-default">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
            
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="facts.html">facts</a></li>
                    <li><a href="facts.html">experience</a></li>
                    <li><a href="facts.html">skills</a></li>
                    <li><a href="facts.html">contacts</a></li>
                    <li><a href="jadwal.html">jadwalku</a></li>
                </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
    </nav>
    {% block content %}{% endblock %}
</body>
</html>

portfolio/templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
<head>
    {% load static %}
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}Hello!{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    

    <!-- Latest compiled and minified CSS -->
   <!-- <link rel="stylesheet" type="text/css" media="screen" href="{% static 'portfolio/css/index.css' %}">-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    
    
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!--<style>
        body {
            font-family: Arial, Helvetica, sans-serif;
        }
    </style>-->
</head>
{% block content %}
   
{% endblock %}

</html>

portfolio/templates/jadwal.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}Jadwal Ane{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>
<body>
    {% block content %}
    <form id="form" action={% url 'portfolio:message_post'} method='POST'>
        {%csrf_token%}
        {{form}}
        <button class="btn btn-primary" type="submit" form="form" value="Submit">Submit</button>
    </form>
    <form id="del" action={% url 'portfolio:delete_recs'} method="GET">
            <button class="btn btn-danger" type="reset" value="Reset">Delete Records</button>
    </form>
    
    <table class="table">
            <thead>
                <th>Name</th>
                <th>Location</th>
                <th>Category</th>
                <th>Event Date</th>
            </thead>
            <tbody>
                {% for i in result %}
                <tr>
                    <td> {{i.name}} </td>
                    <td> {{i.place}} </td>
                    <td> {{i.category}} </td>
                    <td> {{i.date}} </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    {% endblock %}
</body>
</html>